import Phaser from 'phaser'

import {
  ANIM,
  BOMB,
  BOMB_FRAMES,
  COLLECTIBLE_FRAMES,
  DOOR_FRAMES,
  KING_FRAMES,
  PIG_BOMB_FRAMES,
  PIG_FRAMES,
} from '@/constants/GameConstants'
import { ANIM_KEY, TEXTURE_KEY } from '@/constants/keys'

export function registerAnimations(scene: Phaser.Scene): void {
  const create = (
    key: string,
    texture: string,
    frameCount: number,
    frameRate: number,
    loop: boolean,
  ): void => {
    scene.anims.create({
      key,
      frames: scene.anims.generateFrameNumbers(texture, { start: 0, end: frameCount - 1 }),
      frameRate,
      repeat: loop ? -1 : 0,
    })
  }

  create(ANIM_KEY.KING_IDLE, TEXTURE_KEY.KING_IDLE, KING_FRAMES.IDLE, ANIM.IDLE_FPS, true)
  create(ANIM_KEY.KING_RUN, TEXTURE_KEY.KING_RUN, KING_FRAMES.RUN, ANIM.RUN_FPS, true)
  create(ANIM_KEY.KING_JUMP, TEXTURE_KEY.KING_JUMP, KING_FRAMES.JUMP, ANIM.IDLE_FPS, false)
  create(ANIM_KEY.KING_FALL, TEXTURE_KEY.KING_FALL, KING_FRAMES.FALL, ANIM.IDLE_FPS, false)
  create(ANIM_KEY.KING_ATTACK, TEXTURE_KEY.KING_ATTACK, KING_FRAMES.ATTACK, ANIM.ATTACK_FPS, false)
  create(ANIM_KEY.KING_HIT, TEXTURE_KEY.KING_HIT, KING_FRAMES.HIT, ANIM.HIT_FPS, false)
  create(ANIM_KEY.KING_DEAD, TEXTURE_KEY.KING_DEAD, KING_FRAMES.DEAD, ANIM.DEAD_FPS, false)
  create(ANIM_KEY.KING_DOOR_IN, TEXTURE_KEY.KING_DOOR_IN, KING_FRAMES.DOOR_IN, ANIM.KING_DOOR_FPS, false)
  create(ANIM_KEY.KING_DOOR_OUT, TEXTURE_KEY.KING_DOOR_OUT, KING_FRAMES.DOOR_OUT, ANIM.KING_DOOR_FPS, false)

  create(ANIM_KEY.PIG_IDLE, TEXTURE_KEY.PIG_IDLE, PIG_FRAMES.IDLE, ANIM.IDLE_FPS, true)
  create(ANIM_KEY.PIG_RUN, TEXTURE_KEY.PIG_RUN, PIG_FRAMES.RUN, ANIM.RUN_FPS, true)
  create(ANIM_KEY.PIG_ATTACK, TEXTURE_KEY.PIG_ATTACK, PIG_FRAMES.ATTACK, ANIM.ATTACK_FPS, false)
  create(ANIM_KEY.PIG_HIT, TEXTURE_KEY.PIG_HIT, PIG_FRAMES.HIT, ANIM.HIT_FPS, false)
  create(ANIM_KEY.PIG_DEAD, TEXTURE_KEY.PIG_DEAD, PIG_FRAMES.DEAD, ANIM.DEAD_FPS, false)

  create(ANIM_KEY.DOOR_OPENING, TEXTURE_KEY.DOOR_OPENING, DOOR_FRAMES.OPENING, ANIM.DOOR_FPS, false)
  create(ANIM_KEY.DOOR_CLOSING, TEXTURE_KEY.DOOR_CLOSING, DOOR_FRAMES.CLOSING, ANIM.DOOR_FPS, false)

  create(ANIM_KEY.PIG_BOMB_IDLE, TEXTURE_KEY.PIG_BOMB_IDLE, PIG_BOMB_FRAMES.IDLE, ANIM.IDLE_FPS, true)
  create(ANIM_KEY.PIG_BOMB_RUN, TEXTURE_KEY.PIG_BOMB_RUN, PIG_BOMB_FRAMES.RUN, ANIM.RUN_FPS, true)
  create(ANIM_KEY.PIG_BOMB_PICK, TEXTURE_KEY.PIG_BOMB_PICK, PIG_BOMB_FRAMES.PICK, ANIM.ATTACK_FPS, false)
  create(ANIM_KEY.PIG_BOMB_THROW, TEXTURE_KEY.PIG_BOMB_THROW, PIG_BOMB_FRAMES.THROW, ANIM.ATTACK_FPS, false)
  create(ANIM_KEY.BOMB_ON, TEXTURE_KEY.BOMB_ON, BOMB_FRAMES.ON, BOMB.FUSE_FPS, true)
  create(ANIM_KEY.BOMB_BOOM, TEXTURE_KEY.BOMB_BOOM, BOMB_FRAMES.BOOM, BOMB.BOOM_FPS, false)

  create(ANIM_KEY.HEART_IDLE, TEXTURE_KEY.HEART, COLLECTIBLE_FRAMES.HEART, ANIM.IDLE_FPS, true)
  create(ANIM_KEY.BIG_HEART_IDLE, TEXTURE_KEY.BIG_HEART, COLLECTIBLE_FRAMES.HEART, ANIM.IDLE_FPS, true)
  create(ANIM_KEY.DIAMOND_IDLE, TEXTURE_KEY.BIG_DIAMOND, COLLECTIBLE_FRAMES.DIAMOND, ANIM.IDLE_FPS, true)
}
