import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const distHtml = resolve(here, '../dist/index.html')
const outFile = resolve(here, '../../app/src/assets/game/gameHtml.ts')

const html = readFileSync(distHtml, 'utf8')
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')

const contents = `// AUTO-GENERATED by packages/game/scripts/wrap-html.mjs. Do not edit by hand.
export const gameHtml = \`${escaped}\`
`

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, contents)

console.log(`[wrap-html] wrote ${outFile} (${html.length} bytes of HTML)`)
