import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const distDir = resolve(here, '../dist')
const appGameDir = resolve(here, '../../app/src/assets/game')

// 1) the HTML (code + sprites + sfx inlined, music excluded) → a TS string the app
//    writes to disk and serves via file:// so the relative audio paths resolve.
const html = readFileSync(resolve(distDir, 'index.html'), 'utf8')
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')

mkdirSync(appGameDir, { recursive: true })
writeFileSync(
  resolve(appGameDir, 'gameHtml.ts'),
  `// AUTO-GENERATED by packages/game/scripts/wrap-html.mjs. Do not edit by hand.
export const gameHtml = \`${escaped}\`
`,
)

// 2) the music files (emitted separately to dist/audio) → bundled app assets + a
//    manifest, so the app can copy them next to index.html on the device.
const distAudio = resolve(distDir, 'audio')
const appAudio = resolve(appGameDir, 'audio')
mkdirSync(appAudio, { recursive: true })
const audioFiles = readdirSync(distAudio).filter((f) => f.endsWith('.mp3'))
for (const file of audioFiles) {
  copyFileSync(resolve(distAudio, file), resolve(appAudio, file))
}
const manifest = audioFiles.map((file) => `  '${file}': require('./audio/${file}'),`).join('\n')
writeFileSync(
  resolve(appGameDir, 'gameAudio.ts'),
  `// AUTO-GENERATED by packages/game/scripts/wrap-html.mjs. Do not edit by hand.
// Music is bundled as separate assets and served from disk (not inlined).
export const gameAudio: Record<string, number> = {
${manifest}
}
`,
)

console.log(`[wrap-html] wrote gameHtml.ts (${html.length} bytes) + ${audioFiles.length} audio files`)
